In [57]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from scipy.optimize import curve_fit

# Step 1: Load discharge data from Excel file
file_path = 'discharge.xlsx'  # Replace with your actual file path
df = pd.read_excel(file_path)
'''
df['Colonna2'] = pd.to_numeric(df['Colonna2'], errors='coerce')
#df['Colonna1'] = pd.to_datetime(df['Colonna1'], format='%Y-%m-%d', errors='coerce')
df = df.dropna(subset=['Colonna2'])
# Assuming the Excel file has 'Time' and 'Discharge' columns
time = df['Colonna1'].values
discharge = df['Colonna2'].values
print(time)

# Step 2: Define a function to detect recession periods
def detect_recession_periods(time, discharge, threshold=0):
    recessions = []
    current_recession = []
    
    for i in range(1, len(discharge)):
        if discharge[i] < discharge[i - 1]:  # Condition for recession (flow is decreasing)
            current_recession.append((time[i], discharge[i]))
        else:
            if len(current_recession) > 1:  # End of a recession period
                recessions.append(np.array(current_recession))
            current_recession = []
    
    return recessions


# Step 3: Define a function to fit a recession curve (exponential decay model)
def exp_decay(t, a, b):
    return a * np.exp(-b * t)

# Step 4: Create the Master Recession Curve (MRC)
def create_master_recession_curve(recessions):
    master_curve = []
    
    for recession in recessions:
        # Convert datetime values to numeric format (seconds since start)
        t = (recession[:, 0] - recession[0, 0]).astype('timedelta64[s]').astype(float)  # Convert to seconds
        Q = recession[:, 1].astype(float)  # Ensure discharge is float
        
        try:
            # Fit the recession data to the exponential decay model
            params, _ = curve_fit(exp_decay, t, Q)
            a, b = params
            
            # Generate fitted recession curve points
            fitted_curve = exp_decay(t, a, b)
            master_curve.append((t, fitted_curve))
        except RuntimeError:
            pass  # Skip if fitting fails
    
    return master_curve

# Step 5: Plot the Master Recession Curve
def plot_master_curve(master_curve):
    plt.figure(figsize=(10, 6))
    
    for t, fitted_curve in master_curve:
        plt.plot(t, fitted_curve, label="Recession segment")
    
    plt.xlabel('Time (days)')
    plt.ylabel('Discharge (m^3/s)')
    plt.title('Master Recession Curve')
    plt.legend()
    plt.show()

# Main Execution: Detect recessions, create MRC, and plot it

recessions = detect_recession_periods(time, discharge)
master_curve = create_master_recession_curve(recessions)
#plot_master_curve(master_curve)'''

['1992-07-29T00:00:00.000000000' '1992-07-30T00:00:00.000000000'
 '1992-07-31T00:00:00.000000000' ... '2024-01-15T00:00:00.000000000'
 '2024-01-16T00:00:00.000000000' '2024-01-17T00:00:00.000000000']

UFuncTypeError: ufunc 'subtract' cannot use operands with types dtype('O') and dtype('<M8[ns]')

In [55]:
df

1992-11-07T00:00:00.000000000
1992-11-17T00:00:00.000000000
1992-11-29T00:00:00.000000000
1992-12-15T00:00:00.000000000
1992-12-27T00:00:00.000000000
1993-01-04T00:00:00.000000000
1993-01-12T00:00:00.000000000
1993-01-15T00:00:00.000000000
1993-01-25T00:00:00.000000000
1993-02-10T00:00:00.000000000
1993-02-19T00:00:00.000000000
1993-02-23T00:00:00.000000000
1993-11-30T00:00:00.000000000
1993-12-08T00:00:00.000000000
1993-12-13T00:00:00.000000000
1994-01-01T00:00:00.000000000
1994-01-04T00:00:00.000000000
1994-01-18T00:00:00.000000000
1994-01-25T00:00:00.000000000
1994-02-11T00:00:00.000000000
1995-01-02T00:00:00.000000000
1995-01-21T00:00:00.000000000
1995-02-03T00:00:00.000000000
1995-02-11T00:00:00.000000000
1995-02-23T00:00:00.000000000
1995-02-26T00:00:00.000000000
1995-03-19T00:00:00.000000000
1995-03-22T00:00:00.000000000
1995-03-29T00:00:00.000000000
1995-04-02T00:00:00.000000000
1995-04-17T00:00:00.000000000
1995-04-21T00:00:00.000000000
1995-11-25T00:00:00.000000000
1995-12-10T00:00:00.000000000
1995-12-16T00:00:00.000000000
1995-12-24T00:00:00.000000000
1996-01-02T00:00:00.000000000
1996-01-12T00:00:00.000000000
1996-01-23T00:00:00.000000000
1996-01-26T00:00:00.000000000
1996-01-30T00:00:00.000000000
1996-02-07T00:00:00.000000000
1996-02-13T00:00:00.000000000
1996-02-16T00:00:00.000000000
1996-02-20T00:00:00.000000000
1996-02-27T00:00:00.000000000
1996-03-07T00:00:00.000000000
1996-03-17T00:00:00.000000000
1996-03-21T00:00:00.000000000
1996-04-01T00:00:00.000000000
1996-04-10T00:00:00.000000000
1996-07-13T00:00:00.000000000
1996-07-22T00:00:00.000000000
1996-07-26T00:00:00.000000000
1996-08-07T00:00:00.000000000
1996-08-22T00:00:00.000000000
1996-08-26T00:00:00.000000000
1996-09-01T00:00:00.000000000
1996-12-07T00:00:00.000000000
1996-12-16T00:00:00.000000000
1996-12-28T00:00:00.000000000
1997-01-05T00:00:00.000000000
1997-01-10T00:00:00.000000000
1997-01-14T00:00:00.000000000
1997-01-24T00:00:00.000000000
1997-02-01T00:00:00.000000000
1997-02-08T00:00:00.000000000
1997-02-16T00:00:00.000000000
1997-03-02T00:00:00.000000000
1997-03-07T00:00:00.000000000
1997-03-12T00:00:00.000000000
1997-03-24T00:00:00.000000000
1997-04-06T00:00:00.000000000
1997-04-23T00:00:00.000000000
1997-05-01T00:00:00.000000000
1997-05-08T00:00:00.000000000
1997-05-13T00:00:00.000000000
1997-06-08T00:00:00.000000000
1997-07-02T00:00:00.000000000
1997-07-22T00:00:00.000000000
1997-08-17T00:00:00.000000000
1997-08-26T00:00:00.000000000
1997-09-01T00:00:00.000000000
1997-09-05T00:00:00.000000000
1997-09-17T00:00:00.000000000
1997-10-02T00:00:00.000000000
1997-10-19T00:00:00.000000000
1997-12-07T00:00:00.000000000
1998-01-11T00:00:00.000000000
1998-01-21T00:00:00.000000000
1998-01-28T00:00:00.000000000
1998-02-03T00:00:00.000000000
1998-02-25T00:00:00.000000000
1998-03-02T00:00:00.000000000
1998-03-15T00:00:00.000000000
1998-03-21T00:00:00.000000000
1998-03-29T00:00:00.000000000
1998-12-05T00:00:00.000000000
1998-12-14T00:00:00.000000000
1998-12-18T00:00:00.000000000
1998-12-21T00:00:00.000000000
1998-12-25T00:00:00.000000000
1999-01-06T00:00:00.000000000
1999-01-16T00:00:00.000000000
1999-01-24T00:00:00.000000000
1999-02-01T00:00:00.000000000
1999-02-09T00:00:00.000000000
1999-02-25T00:00:00.000000000
1999-03-09T00:00:00.000000000
1999-05-23T00:00:00.000000000
1999-11-28T00:00:00.000000000
1999-12-01T00:00:00.000000000
1999-12-16T00:00:00.000000000
2000-12-16T00:00:00.000000000
2000-12-23T00:00:00.000000000
2001-01-21T00:00:00.000000000
2001-02-07T00:00:00.000000000
2001-02-17T00:00:00.000000000
2001-03-01T00:00:00.000000000
2001-03-05T00:00:00.000000000
2001-03-13T00:00:00.000000000
2001-03-21T00:00:00.000000000
2001-03-24T00:00:00.000000000
2001-03-30T00:00:00.000000000
2001-04-06T00:00:00.000000000
2001-04-13T00:00:00.000000000
2001-04-17T00:00:00.000000000
2001-04-23T00:00:00.000000000
2001-04-29T00:00:00.000000000
2001-05-05T00:00:00.000000000
2001-05-21T00:00:00.000000000
2001-06-25T00:00:00.000000000
2001-07-20T00:00:00.000000000
2001-08-04T00:00:00.000000000
2001-11-23T00:00:00.000000000
2001-12-02T00:00:00.000000000
2001-12-08T00:00:00.000000000
2001-12-19T00:00:00.000000000
2001-12-23T00:00:00.000000000
2001-12-31T00:00:00.000000000
2002-01-10T00:00:00.000000000
2002-01-14T00:00:00.000000000
2002-01-19T00:00:00.000000000
2002-02-04T00:00:00.000000000
2002-02-12T00:00:00.000000000
2002-03-03T00:00:00.000000000
2002-06-24T00:00:00.000000000
2002-08-16T00:00:00.000000000
2002-10-06T00:00:00.000000000
2002-11-28T00:00:00.000000000
2002-12-20T00:00:00.000000000
2003-01-11T00:00:00.000000000
2003-01-29T00:00:00.000000000
2003-02-25T00:00:00.000000000
2003-02-28T00:00:00.000000000
2003-03-09T00:00:00.000000000
2003-03-23T00:00:00.000000000
2003-03-27T00:00:00.000000000
2003-04-13T00:00:00.000000000
2003-04-17T00:00:00.000000000
2003-06-08T00:00:00.000000000
2003-06-12T00:00:00.000000000
2003-08-29T00:00:00.000000000
2003-10-24T00:00:00.000000000
2003-10-31T00:00:00.000000000
2003-12-01T00:00:00.000000000
2003-12-13T00:00:00.000000000
2003-12-17T00:00:00.000000000
2003-12-26T00:00:00.000000000
2004-01-09T00:00:00.000000000
2004-01-18T00:00:00.000000000
2004-01-25T00:00:00.000000000
2004-02-08T00:00:00.000000000
2004-02-16T00:00:00.000000000
2004-02-21T00:00:00.000000000
2004-02-29T00:00:00.000000000
2004-03-08T00:00:00.000000000
2004-03-13T00:00:00.000000000
2004-03-18T00:00:00.000000000
2004-03-28T00:00:00.000000000
2004-04-13T00:00:00.000000000
2004-04-24T00:00:00.000000000
2004-05-01T00:00:00.000000000
2004-05-29T00:00:00.000000000
2004-06-06T00:00:00.000000000
2004-06-14T00:00:00.000000000
2004-06-30T00:00:00.000000000
2004-07-08T00:00:00.000000000
2004-07-16T00:00:00.000000000
2004-07-21T00:00:00.000000000
2004-07-29T00:00:00.000000000
2004-11-25T00:00:00.000000000
2004-12-05T00:00:00.000000000
2004-12-12T00:00:00.000000000
2005-01-25T00:00:00.000000000
2005-02-14T00:00:00.000000000
2005-02-26T00:00:00.000000000
2005-03-08T00:00:00.000000000
2005-03-13T00:00:00.000000000
2005-04-01T00:00:00.000000000
2005-04-04T00:00:00.000000000
2005-05-21T00:00:00.000000000
2005-05-31T00:00:00.000000000
2005-08-19T00:00:00.000000000
2005-08-26T00:00:00.000000000
2005-10-08T00:00:00.000000000
2005-11-08T00:00:00.000000000
2005-12-06T00:00:00.000000000
2005-12-12T00:00:00.000000000
2005-12-22T00:00:00.000000000
2005-12-29T00:00:00.000000000
2006-01-06T00:00:00.000000000
2006-01-14T00:00:00.000000000
2006-01-27T00:00:00.000000000
2006-02-01T00:00:00.000000000
2006-02-05T00:00:00.000000000
2006-02-13T00:00:00.000000000
2006-02-18T00:00:00.000000000
2006-03-03T00:00:00.000000000
2006-03-09T00:00:00.000000000
2006-03-18T00:00:00.000000000
2006-03-30T00:00:00.000000000
2006-04-22T00:00:00.000000000
2006-04-27T00:00:00.000000000
2006-05-01T00:00:00.000000000
2006-05-06T00:00:00.000000000
2006-05-13T00:00:00.000000000
2006-05-18T00:00:00.000000000
2006-05-27T00:00:00.000000000
2006-06-06T00:00:00.000000000
2006-06-12T00:00:00.000000000
2006-06-28T00:00:00.000000000
2006-07-03T00:00:00.000000000
2006-08-16T00:00:00.000000000
2006-09-24T00:00:00.000000000
2006-11-06T00:00:00.000000000
2006-11-25T00:00:00.000000000
2006-11-29T00:00:00.000000000
2006-12-15T00:00:00.000000000
2006-12-19T00:00:00.000000000
2006-12-22T00:00:00.000000000
2007-01-04T00:00:00.000000000
2007-01-15T00:00:00.000000000
2007-02-28T00:00:00.000000000
2007-03-07T00:00:00.000000000
2007-03-14T00:00:00.000000000
2007-03-31T00:00:00.000000000
2007-06-27T00:00:00.000000000
2007-09-07T00:00:00.000000000
2007-09-12T00:00:00.000000000
2007-10-01T00:00:00.000000000
2007-10-05T00:00:00.000000000
2007-10-13T00:00:00.000000000
2007-10-27T00:00:00.000000000
2007-11-09T00:00:00.000000000
2007-11-25T00:00:00.000000000
2007-11-29T00:00:00.000000000
2007-12-02T00:00:00.000000000
2007-12-05T00:00:00.000000000
2007-12-18T00:00:00.000000000
2007-12-21T00:00:00.000000000
2008-01-03T00:00:00.000000000
2008-01-11T00:00:00.000000000
2008-01-29T00:00:00.000000000
2008-02-03T00:00:00.000000000
2008-02-16T00:00:00.000000000
2008-03-01T00:00:00.000000000
2008-03-14T00:00:00.000000000
2008-03-21T00:00:00.000000000
2008-03-28T00:00:00.000000000
2008-04-11T00:00:00.000000000
2008-04-16T00:00:00.000000000
2008-05-21T00:00:00.000000000
2008-06-03T00:00:00.000000000
2008-06-10T00:00:00.000000000
2008-06-15T00:00:00.000000000
2008-06-26T00:00:00.000000000
2008-07-08T00:00:00.000000000
2008-07-17T00:00:00.000000000
2008-07-27T00:00:00.000000000
2008-08-14T00:00:00.000000000
2009-01-01T00:00:00.000000000
2009-01-17T00:00:00.000000000
2009-01-21T00:00:00.000000000
2009-02-02T00:00:00.000000000
2009-02-08T00:00:00.000000000
2009-02-21T00:00:00.000000000
2009-03-07T00:00:00.000000000
2009-03-18T00:00:00.000000000
2009-03-24T00:00:00.000000000
2009-03-31T00:00:00.000000000
2009-05-25T00:00:00.000000000
2009-06-01T00:00:00.000000000
2009-06-08T00:00:00.000000000
2009-06-22T00:00:00.000000000
2009-07-05T00:00:00.000000000
2009-07-15T00:00:00.000000000
2009-07-25T00:00:00.000000000
2009-08-12T00:00:00.000000000
2009-10-27T00:00:00.000000000
2009-11-22T00:00:00.000000000
2009-12-05T00:00:00.000000000
2009-12-16T00:00:00.000000000
2009-12-24T00:00:00.000000000
2009-12-27T00:00:00.000000000
2010-01-01T00:00:00.000000000
2010-01-09T00:00:00.000000000
2010-01-22T00:00:00.000000000
2010-02-08T00:00:00.000000000
2010-02-20T00:00:00.000000000
2010-03-04T00:00:00.000000000
2010-03-24T00:00:00.000000000
2010-04-03T00:00:00.000000000
2010-04-09T00:00:00.000000000
2010-04-12T00:00:00.000000000
2010-04-21T00:00:00.000000000
2010-04-28T00:00:00.000000000
2010-05-09T00:00:00.000000000
2010-05-14T00:00:00.000000000
2010-05-21T00:00:00.000000000
2010-05-24T00:00:00.000000000
2010-06-05T00:00:00.000000000
2010-06-09T00:00:00.000000000
2010-07-06T00:00:00.000000000
2010-07-10T00:00:00.000000000
2010-07-16T00:00:00.000000000
2010-07-24T00:00:00.000000000
2010-07-27T00:00:00.000000000
2010-08-10T00:00:00.000000000
2010-08-18T00:00:00.000000000
2010-08-24T00:00:00.000000000
2010-09-06T00:00:00.000000000
2010-09-14T00:00:00.000000000
2010-09-19T00:00:00.000000000
2010-09-23T00:00:00.000000000
2010-09-27T00:00:00.000000000
2010-10-02T00:00:00.000000000
2010-10-06T00:00:00.000000000
2010-10-26T00:00:00.000000000
2010-10-29T00:00:00.000000000
2010-11-06T00:00:00.000000000
2010-11-10T00:00:00.000000000
2010-11-14T00:00:00.000000000
2010-11-18T00:00:00.000000000
2010-12-01T00:00:00.000000000
2010-12-09T00:00:00.000000000
2010-12-16T00:00:00.000000000
2010-12-22T00:00:00.000000000
2010-12-27T00:00:00.000000000
2011-01-05T00:00:00.000000000
2011-01-10T00:00:00.000000000
2011-01-19T00:00:00.000000000
2011-01-22T00:00:00.000000000
2011-01-29T00:00:00.000000000
2011-02-02T00:00:00.000000000
2011-03-02T00:00:00.000000000
2011-03-16T00:00:00.000000000
2011-03-25T00:00:00.000000000
2011-04-01T00:00:00.000000000
2011-04-09T00:00:00.000000000
2011-04-23T00:00:00.000000000
2011-04-28T00:00:00.000000000
2011-05-13T00:00:00.000000000
2011-05-24T00:00:00.000000000
2011-06-21T00:00:00.000000000
2011-07-12T00:00:00.000000000
2011-07-17T00:00:00.000000000
2011-07-24T00:00:00.000000000
2011-07-31T00:00:00.000000000
2011-08-05T00:00:00.000000000
2011-08-09T00:00:00.000000000
2011-08-14T00:00:00.000000000
2011-08-23T00:00:00.000000000
2011-08-27T00:00:00.000000000
2011-08-31T00:00:00.000000000
2011-09-07T00:00:00.000000000
2011-09-14T00:00:00.000000000
2011-09-19T00:00:00.000000000
2011-09-30T00:00:00.000000000
2011-10-04T00:00:00.000000000
2011-11-26T00:00:00.000000000
2011-12-01T00:00:00.000000000
2011-12-08T00:00:00.000000000
2011-12-12T00:00:00.000000000
2011-12-18T00:00:00.000000000
2012-01-03T00:00:00.000000000
2012-01-07T00:00:00.000000000
2012-01-17T00:00:00.000000000
2012-01-23T00:00:00.000000000
2012-01-28T00:00:00.000000000
2012-02-01T00:00:00.000000000
2012-02-15T00:00:00.000000000
2012-03-31T00:00:00.000000000
2012-04-19T00:00:00.000000000
2012-05-03T00:00:00.000000000
2012-05-14T00:00:00.000000000
2012-05-24T00:00:00.000000000
2012-06-09T00:00:00.000000000
2012-06-16T00:00:00.000000000
2012-06-21T00:00:00.000000000
2012-07-01T00:00:00.000000000
2012-07-08T00:00:00.000000000
2012-07-22T00:00:00.000000000
2012-08-05T00:00:00.000000000
2012-09-23T00:00:00.000000000
2012-10-14T00:00:00.000000000
2012-10-18T00:00:00.000000000
2012-10-22T00:00:00.000000000
2012-10-31T00:00:00.000000000
2012-11-07T00:00:00.000000000
2012-11-11T00:00:00.000000000
2012-11-18T00:00:00.000000000
2012-11-24T00:00:00.000000000
2012-11-29T00:00:00.000000000
2012-12-07T00:00:00.000000000
2012-12-11T00:00:00.000000000
2012-12-17T00:00:00.000000000
2012-12-21T00:00:00.000000000
2012-12-30T00:00:00.000000000
2013-01-06T00:00:00.000000000
2013-01-11T00:00:00.000000000
2013-01-17T00:00:00.000000000
2013-01-22T00:00:00.000000000
2013-02-06T00:00:00.000000000
2013-03-03T00:00:00.000000000
2013-03-10T00:00:00.000000000
2013-03-13T00:00:00.000000000
2013-03-17T00:00:00.000000000
2013-03-30T00:00:00.000000000
2013-04-07T00:00:00.000000000
2013-04-13T00:00:00.000000000
2013-04-23T00:00:00.000000000
2013-04-27T00:00:00.000000000
2013-05-03T00:00:00.000000000
2013-05-17T00:00:00.000000000
2013-06-13T00:00:00.000000000
2013-06-27T00:00:00.000000000
2013-07-04T00:00:00.000000000
2013-07-07T00:00:00.000000000
2013-07-15T00:00:00.000000000
2013-07-29T00:00:00.000000000
2013-08-24T00:00:00.000000000
2013-09-08T00:00:00.000000000
2013-09-14T00:00:00.000000000
2013-09-18T00:00:00.000000000
2013-09-23T00:00:00.000000000
2013-10-02T00:00:00.000000000
2013-10-09T00:00:00.000000000
2013-10-17T00:00:00.000000000
2013-10-23T00:00:00.000000000
2013-10-26T00:00:00.000000000
2013-11-02T00:00:00.000000000
2013-11-06T00:00:00.000000000
2013-11-12T00:00:00.000000000
2013-11-18T00:00:00.000000000
2013-11-25T00:00:00.000000000
2013-12-04T00:00:00.000000000
2013-12-10T00:00:00.000000000
2013-12-22T00:00:00.000000000
2014-01-01T00:00:00.000000000
2014-01-13T00:00:00.000000000
2014-02-03T00:00:00.000000000
2014-02-09T00:00:00.000000000
2014-02-20T00:00:00.000000000
2014-02-24T00:00:00.000000000
2014-03-07T00:00:00.000000000
2014-03-14T00:00:00.000000000
2014-03-18T00:00:00.000000000
2014-04-07T00:00:00.000000000
2014-04-10T00:00:00.000000000
2014-04-24T00:00:00.000000000
2014-05-09T00:00:00.000000000
2014-06-05T00:00:00.000000000
2014-06-09T00:00:00.000000000
2014-06-19T00:00:00.000000000
2014-07-15T00:00:00.000000000
2014-07-19T00:00:00.000000000
2014-07-22T00:00:00.000000000
2014-07-28T00:00:00.000000000
2014-08-03T00:00:00.000000000
2014-08-19T00:00:00.000000000
2014-08-26T00:00:00.000000000
2014-09-04T00:00:00.000000000
2014-09-07T00:00:00.000000000
2014-09-16T00:00:00.000000000
2014-09-21T00:00:00.000000000
2014-09-27T00:00:00.000000000
2014-09-30T00:00:00.000000000
2014-10-07T00:00:00.000000000
2014-10-12T00:00:00.000000000
2014-10-17T00:00:00.000000000
2014-10-24T00:00:00.000000000
2014-10-28T00:00:00.000000000
2014-11-09T00:00:00.000000000
2014-11-19T00:00:00.000000000
2014-12-01T00:00:00.000000000
2014-12-19T00:00:00.000000000
2014-12-22T00:00:00.000000000
2014-12-30T00:00:00.000000000
2015-01-03T00:00:00.000000000
2015-01-28T00:00:00.000000000
2015-02-04T00:00:00.000000000
2015-02-07T00:00:00.000000000
2015-02-16T00:00:00.000000000
2015-03-01T00:00:00.000000000
2015-03-08T00:00:00.000000000
2015-03-14T00:00:00.000000000
2015-03-19T00:00:00.000000000
2015-03-25T00:00:00.000000000
2015-03-29T00:00:00.000000000
2015-04-13T00:00:00.000000000
2015-04-17T00:00:00.000000000
2015-04-21T00:00:00.000000000
2015-04-27T00:00:00.000000000
2015-04-30T00:00:00.000000000
2015-05-05T00:00:00.000000000
2015-05-28T00:00:00.000000000
2015-06-10T00:00:00.000000000
2015-06-19T00:00:00.000000000
2015-06-30T00:00:00.000000000
2015-07-09T00:00:00.000000000
2015-08-01T00:00:00.000000000
2015-09-11T00:00:00.000000000
2015-10-01T00:00:00.000000000
2015-10-23T00:00:00.000000000
2015-11-03T00:00:00.000000000
2015-11-11T00:00:00.000000000
2015-11-18T00:00:00.000000000
2015-11-22T00:00:00.000000000
2015-11-29T00:00:00.000000000
2015-12-06T00:00:00.000000000
2015-12-11T00:00:00.000000000
2015-12-17T00:00:00.000000000
2015-12-20T00:00:00.000000000
2015-12-28T00:00:00.000000000
2016-01-01T00:00:00.000000000
2016-01-12T00:00:00.000000000
2016-01-18T00:00:00.000000000
2016-02-03T00:00:00.000000000
2016-02-10T00:00:00.000000000
2016-02-15T00:00:00.000000000
2016-02-19T00:00:00.000000000
2016-02-24T00:00:00.000000000
2016-02-29T00:00:00.000000000
2016-03-04T00:00:00.000000000
2016-03-13T00:00:00.000000000
2016-03-23T00:00:00.000000000
2016-03-29T00:00:00.000000000
2016-04-15T00:00:00.000000000
2016-04-19T00:00:00.000000000
2016-04-25T00:00:00.000000000
2016-04-28T00:00:00.000000000
2016-05-03T00:00:00.000000000
2016-05-06T00:00:00.000000000
2016-05-09T00:00:00.000000000
2016-05-12T00:00:00.000000000
2016-05-17T00:00:00.000000000
2016-05-22T00:00:00.000000000
2016-05-28T00:00:00.000000000
2016-06-04T00:00:00.000000000
2016-06-07T00:00:00.000000000
2016-06-14T00:00:00.000000000
2016-06-19T00:00:00.000000000
2016-06-25T00:00:00.000000000
2016-07-01T00:00:00.000000000
2016-07-06T00:00:00.000000000
2016-07-14T00:00:00.000000000
2016-07-19T00:00:00.000000000
2016-07-27T00:00:00.000000000
2016-08-03T00:00:00.000000000
2016-08-06T00:00:00.000000000
2016-08-13T00:00:00.000000000
2016-08-18T00:00:00.000000000
2016-09-02T00:00:00.000000000
2016-09-07T00:00:00.000000000
2016-09-12T00:00:00.000000000
2016-09-15T00:00:00.000000000
2016-09-20T00:00:00.000000000
2016-09-27T00:00:00.000000000
2016-10-06T00:00:00.000000000
2016-10-11T00:00:00.000000000
2016-10-15T00:00:00.000000000
2016-10-19T00:00:00.000000000
2016-10-24T00:00:00.000000000
2016-10-27T00:00:00.000000000
2016-11-04T00:00:00.000000000
2016-11-17T00:00:00.000000000
2016-11-22T00:00:00.000000000
2016-12-01T00:00:00.000000000
2016-12-07T00:00:00.000000000
2016-12-20T00:00:00.000000000
2016-12-26T00:00:00.000000000
2017-01-01T00:00:00.000000000
2017-01-10T00:00:00.000000000
2017-01-15T00:00:00.000000000
2017-01-19T00:00:00.000000000
2017-01-27T00:00:00.000000000
2017-02-02T00:00:00.000000000
2017-02-09T00:00:00.000000000
2017-02-20T00:00:00.000000000
2017-03-01T00:00:00.000000000
2017-03-09T00:00:00.000000000
2017-04-09T00:00:00.000000000
2017-04-18T00:00:00.000000000
2017-04-25T00:00:00.000000000
2017-05-09T00:00:00.000000000
2017-05-23T00:00:00.000000000
2017-05-27T00:00:00.000000000
2017-05-30T00:00:00.000000000
2017-06-13T00:00:00.000000000
2017-06-20T00:00:00.000000000
2017-06-26T00:00:00.000000000
2017-07-03T00:00:00.000000000
2017-07-09T00:00:00.000000000
2017-07-12T00:00:00.000000000
2017-07-15T00:00:00.000000000
2017-07-19T00:00:00.000000000
2017-07-28T00:00:00.000000000
2017-08-02T00:00:00.000000000
2017-08-11T00:00:00.000000000
2017-08-16T00:00:00.000000000
2017-08-22T00:00:00.000000000
2017-08-29T00:00:00.000000000
2017-09-01T00:00:00.000000000
2017-09-06T00:00:00.000000000
2017-09-16T00:00:00.000000000
2017-09-20T00:00:00.000000000
2017-10-02T00:00:00.000000000
2017-10-06T00:00:00.000000000
2017-10-11T00:00:00.000000000
2017-10-22T00:00:00.000000000
2017-11-02T00:00:00.000000000
2017-11-06T00:00:00.000000000
2017-11-13T00:00:00.000000000
2017-11-17T00:00:00.000000000
2017-11-29T00:00:00.000000000
2017-12-09T00:00:00.000000000
2017-12-16T00:00:00.000000000
2017-12-22T00:00:00.000000000
2017-12-26T00:00:00.000000000
2017-12-29T00:00:00.000000000
2018-01-15T00:00:00.000000000
2018-02-08T00:00:00.000000000
2018-02-23T00:00:00.000000000
2018-03-01T00:00:00.000000000
2018-03-20T00:00:00.000000000
2018-03-25T00:00:00.000000000
2018-03-29T00:00:00.000000000
2018-04-05T00:00:00.000000000
2018-04-11T00:00:00.000000000
2018-04-17T00:00:00.000000000
2018-04-23T00:00:00.000000000
2018-04-30T00:00:00.000000000
2018-05-04T00:00:00.000000000
2018-05-11T00:00:00.000000000
2018-05-20T00:00:00.000000000
2018-06-01T00:00:00.000000000
2018-06-06T00:00:00.000000000
2018-06-09T00:00:00.000000000
2018-06-22T00:00:00.000000000
2018-07-06T00:00:00.000000000
2018-07-17T00:00:00.000000000
2018-07-25T00:00:00.000000000
2018-08-10T00:00:00.000000000
2018-09-06T00:00:00.000000000
2018-09-19T00:00:00.000000000

In [54]:
for recession in recessions:
        # Convert datetime values to numeric format (seconds since start)
        t = (recession[:, 0] - recession[0, 0]).astype('timedelta64[s]').astype(float)

UFuncTypeError: ufunc 'subtract' cannot use operands with types dtype('O') and dtype('<M8[ns]')